[package]
name = "rust_example"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = { version = "1.4", features = ["spin_no_std"] }

[lib]
crate-type = ["staticlib"]
